### PR TITLE
Added 4 sessions (JAM47, JAM49, JAM847, JAM849)

### PR DESCRIPTION
**Pull request by MSohm**
Added JAM47 and JAM49 to Americas.
Added JAM847 and JAM849 to Asia.

### CODE REVIEW

**Comment by pelegri** [comment]
I know the bucketlist is an earlier version of the current, reviewed, code.  But,  I peeked into one of those ZIPs and I didn't see a LICENSE file.  I assume the rest went through review but, can you do another pass, add the missing LICENSE files and, if necessary, do a fast internal review?   Thanks,

**Comment by MSohm** [comment]
None of the code in these samples went through review.  The sample that was reviewed was modified a fair amount by the Cascades team.

Since these samples no longer work anyway, it may be better to just add in the presentations (JAM47 & JAM847) and not the lab content.

Can you merge just those or should I do another pull request?

**Comment by pelegri** [comment]
I agree w/ you Mark, delete the ZIPs and just point to the new versions of the samples.   I believe that if you delete the files from your repo then the pull request will be automatically updated.    You can give it a try and check.  Or I can close the pull request, but then you have to delete anyhow; might as well try first.

**Comment by MSohm** [comment]
I removed JAM49 and JAM849.  Did the pull request update?

**Comment by pelegri** [comment]
Yep, it did...  Is this productive, or what? :)

Merging it now.

**Pull request merged**
