### PR TITLE
Add camera session JAM370 from Jamsterdam.

### PR DESCRIPTION
**Pull request by seanmcveigh**
Camera3D is first sample.  the rest are on the way.

### CODE REVIEW

**Comment by pelegri** [comment]
Works for me.  Did Richard check do a quick pass on it?

**Comment by seanmcveigh** [comment]
Yup.
More on the way

Sent from my BlackBerry 10 smartphone on the Rogers network.
From: Eduardo Pelegri-Llopart
Sent: Sunday, June 16, 2013 5:46 PM
To: blackberry/Presentations
Reply To: blackberry/Presentations
Cc: Sean McVeigh
Subject: Re: [Presentations] Add camera session JAM370 from Jamsterdam. (#35)

Works for me. Did Richard check do a quick pass on it?

**Comment by seanmcveigh** [comment]
still open?
I don't want to get overlapping pull requests to the same repo underway, as that gets annoying to manage.  Waiting for this one to be closed before the next one comes in... :)

**Comment by pelegri** [comment]
Sorry, traveling...

**Pull request merged**
