### PR TITLE
Switched from ic_open.png to my_open.png

### PR DESCRIPTION
**Pull request by pelegri**
Requesting review by two of @djclayworth, @mkoch and @kwallis

### CODE REVIEW

**Comment by DJClayworth** [comment]
Please do not do this. By doing this we are encouraging our developers to use non-standard icons, which we do not want to be encouraging. This issue should be addressed by fixing the license agreement, not by carrying out a coding practice we would prefer our developers avoid.

**Comment by mkoch** [comment]
we're not sure we can switch the license but @pelegri has started that conversation:

http://github.rim.net/OpenBerry/OpenBerry/issues/419

**Comment by pelegri** [comment]
Let's continue the conversation internally, but, from what I can see, the license on those assets won't get fixed anytime soon, specially given all the other distractions going on.

**Comment by pelegri** [comment]
Applying the icon change now...

**Pull request merged**
